spring:
  application:
    name: gateway

  #  data:
  #    redis:
  #      host: ${REDIS_HOST:localhost}
  #      port: ${REDIS_PORT:6379}
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_HOST}:${REDIS_PORT}
      ssl:
        enabled: true

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins:
              - http://localhost:3000
              - https://bloom-chil.com
              - https://api.bloom-chil.com
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allowed-headers:
              - "*"

      server:
        webflux:
          routes:
            - id: auth-api-docs
              uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8081}
              predicates:
                - Path=/v3/api-docs/auth
              filters:
                - RewritePath=/v3/api-docs/auth, /v3/api-docs

            - id: greenroom-api-docs
              uri: http://${GREENROOM_SERVER_HOST:localhost}:${GREENROOM_SERVER_PORT:8082}
              predicates:
                - Path=/v3/api-docs/greenroom
              filters:
                - RewritePath=/v3/api-docs/greenroom, /v3/api-docs

            - id: notification-api-docs
              uri: http://${NOTIFICATION_SERVER_HOST:localhost}:${NOTIFICATION_SERVER_PORT:8083}
              predicates:
                - Path=/v3/api-docs/notification
              filters:
                - RewritePath=/v3/api-docs/notification, /v3/api-docs

            - id: auth-jwt
              uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8081}
              predicates:
                - Path=/auth/logout, /auth/me, /auth/consent, /auth/notifications/preference, /auth/profile-images/**, /admin/users/invite, /users/me
              filters:
                - JwtAuthenticationFilter

            - id: auth
              uri: http://${AUTH_SERVER_HOST:localhost}:${AUTH_SERVER_PORT:8081}
              predicates:
                - Path=/auth/**

            - id: greenroom-ai
              uri: http://${GREENROOM_SERVER_HOST:localhost}:${GREENROOM_SERVER_PORT:8082}
              predicates:
                - Path=/greenroom/ai, /greenroom/ai/**

            - id: greenroom
              uri: http://${GREENROOM_SERVER_HOST:localhost}:${GREENROOM_SERVER_PORT:8082}
              predicates:
                - Path=/greenroom/**
              filters:
                - JwtAuthenticationFilter

            - id: notification
              uri: http://${NOTIFICATION_SERVER_HOST:localhost}:${NOTIFICATION_SERVER_PORT:8083}
              predicates:
                - Path=/notification/**
              filters:
                - JwtAuthenticationFilter

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth
        url: /v3/api-docs/auth
      - name: greenroom
        url: /v3/api-docs/greenroom
      - name: notification
        url: /v3/api-docs/notification
  api-docs:
    enabled: true

jwt:
  secret: ${kt.jwt.secret:kt-cloud-tech-up-final-project-2026020201010101}
  access-token-expiration: ${kt.jwt.access-token-expiration:300000}
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000}
